### PR TITLE
Implement microfacet based MaterialX closures

### PR DESCRIPTION
**Pull request by fpsunflower**
Another round of MaterialX closure support. Refraction and energy conservation/albedo is still TODO ...

### CODE REVIEW

**Comment by fpsunflower** [comment]
@lgritz the testsuite failures appear to be unrelated to this change. Did something change on the OIIO side maybe?

**Comment by fpsunflower** [comment]
Updated with refraction support.

**Comment by lgritz** [comment]
I'm testing a fix for the mismatched images, stand by...

**Comment by lgritz** [comment]
I think I have a fix, but no matter what I try, I can't seem to push an update to your branch (I know it's let me do that before).

So I pushed my fixes (as well as rebasing on to of current main) to lgritz/mx-fresnel. Can you please grab that, and then re-push it as fpsunflower/mx-fresnel, and then I think we're ready to go?

**Comment by fpsunflower** [comment]
Will take a look tonight. Thanks!

**Comment by lgritz** [comment]
Because I know I can repair this with a single small patch on top, I'm just going to merge this as-is and then just do my fix subsequently.

**Pull request merged**
