### PR TITLE
Fix color conversion from RGB to xyY

### PR DESCRIPTION
**Pull request by ix-bruiz**
## Description

Fix color conversion from RGB to xyY space.

## Tests

Added testcase for xyY conversion in transformc testsuite.

## Checklist:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [ ] I have previously submitted a [Contributor License Agreement](http://opensource.imageworks.com/cla/).
- [ ] I have updated the documentation, if applicable.
- [x] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project.

### CODE REVIEW

**Comment by lgritz** [comment]
I believe this need an update of test reference output.

**Comment by ix-bruiz** [comment]
Indeed! Didn't notice it wasn't automatically updated! Should be good now.

**Comment by ix-bruiz** [comment]
I also pushed a fix regarding test compilation on Windows, where casting nullptr to intptr_t is invalid.

**Review by lgritz — APPROVED** [review]
LGTM, thanks for the fix!

**Pull request merged**
