### PR TITLE
Fix for LLVM 12 compatibilty 

### PR DESCRIPTION
**Pull request by luyatshimbalanga**
## Description
This patch fixes a compatibility with LLVM 13 and up based on [this change](https://reviews.llvm.org/D101650) and the possible removal of [StackAlignmentOverride](https://reviews.llvm.org/D103048).

## Tests

Available resulting test 

## Patch:
[osl-llvm12.diff.txt](https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/files/7109042/osl-llvm12.diff.txt)

```
diff -Naur OpenShadingLanguage-Release-1.11.15.0.orig/src/liboslexec/llvm_util.cpp OpenShadingLanguage-Release-1.11.15.0/src/liboslexec/llvm_util.cpp
--- OpenShadingLanguage-Release-1.11.15.0.orig/src/liboslexec/llvm_util.cpp	2021-09-01 00:26:06.000000000 -0700
+++ OpenShadingLanguage-Release-1.11.15.0/src/liboslexec/llvm_util.cpp	2021-09-03 17:14:01.840127907 -0700
@@ -1228,7 +1228,9 @@
 
     options.NoZerosInBSS = false;
     options.GuaranteedTailCallOpt = false;
+#if OSL_LLVM_VERSION < 120
     options.StackAlignmentOverride = 0;
+#endif
     options.FunctionSections = true;
     options.UseInitArray = false;
     options.FloatABIType = llvm::FloatABI::Default;
@@ -2989,7 +2991,7 @@
 LLVM_Util::write_bitcode_file (const char *filename, std::string *err)
 {
     std::error_code local_error;
-    llvm::raw_fd_ostream out (filename, local_error, llvm::sys::fs::F_None);
+    llvm::raw_fd_ostream out (filename, local_error, llvm::sys::fs::OF_None);
     if (! out.has_error()) {
         llvm::WriteBitcodeToFile (*module(), out);
         if (err && local_error)
@@ -3051,7 +3053,9 @@
     options.AllowFPOpFusion                        = llvm::FPOpFusion::Fast;
     options.NoZerosInBSS                           = 0;
     options.GuaranteedTailCallOpt                  = 0;
+#if OSL_LLVM_VERSION < 120 
     options.StackAlignmentOverride                 = 0;
+#endif    
     options.UseInitArray                           = 0;
 
     llvm::TargetMachine* target_machine = llvm_target->createTargetMachine(

```

## Checklist:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] I have previously submitted a [Contributor License Agreement](http://opensource.imageworks.com/cla/).
- [ ] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project.

### CODE REVIEW

**Comment by lgritz** [comment]
I'm not sure what's going on with this, but can you please rebase on the top of the current master for this PR?

**Comment by lgritz** [comment]
I think I see. These ARE changes on top of master, but somehow when you submitted the PR, you told GitHub you were submitted it against release rather than against master, so this makes it think the patch consists of EVERYTHING it would take to turn release into master. Are you able to edit that on your end? If not, then I suggest closing and file a new PR, but this time be sure GH knows that you're intending for it to be a patch against master.

**Comment by lgritz** [comment]
Ping!

Can you please either alter the PR so that you are submitting *to* release instead of to master? Or rebase your changes on the current master?

**Comment by luyatshimbalanga** [comment]
> Ping!
> 
> Can you please either alter the PR so that you are submitting _to_ release instead of to master? Or rebase your changes on the current master?
I am closing this pull request as it is now moved to #1412

**Pull request closed without merging**
