### PR TITLE
ci: test against LLVM 17

### PR DESCRIPTION
**Pull request by lgritz**
Bump the "bleeding edge" test to LLVM 17, the "stable latest releases" test to 16.

### CODE REVIEW

**Comment by lgritz** [comment]
Does this seem ok?

**Comment by AlexMWells** [comment]
So which clang versions will CI be exercising now?

**Comment by lgritz** [comment]
Clang or LLVM?

With this test, I believe our CI will test against llvm (for JIT) with every major version from 9 to 17, inclusive. (That actually feels like unnecessarily many, maybe it's time to raise the minimum for future OSL 1.14+ releases?)

But our CI only builds with a few versions of clang: 9, 13, and 14 (on Linux), and 15 (on Mac). Most of our build matrix uses gcc, plus the icc & icx tests. It would be unwieldy to expand the CI tests to make every combination test against every compiler, so we kind of sample. Historically, we have rarely or never found much sensitivity to building against one or another version of clang, as long as they both support the same level of C++ standard.

The one exception is that sometimes newer versions monotonically add new warnings, so we should always be doing one build with the very latest clang to make sure we compile cleanly with no warnings. I'll amend this PR to make sure one build uses the latest clang 17 to ensure we have full coverage there.

**Comment by lgritz** [comment]
Amended: Test clang 17 compilation with MacOS-13 build

**Review by brechtvl — APPROVED** [review]

**Pull request merged**
