### PR TITLE
windows compile fix

### PR DESCRIPTION
**Pull request by debaetsd**
## Description

This tiny PR fixes a compile error on Windows

## Tests

it compiles on windows while without this, it does not
CI should catch any regressions wrt other platforms

## Checklist:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] I have previously submitted a [Contributor License Agreement](http://opensource.imageworks.com/cla/).
- [ ] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).
- [ ] My code follows the prevailing code style of this project.

### CODE REVIEW

**Review by lgritz — APPROVED** [review]
LGTM, thanks for the fix.

**Comment by lgritz** [comment]
The CLA bot thinks you don't gave a CLA on file. If you think you already filed one, then are you maybe using a different github ID or email than usual?

**Comment by debaetsd** [comment]
@lgritz I had indeed used the wrong email (hence the force pushed commit) but at the same time I hadn't signed the post-ASWF-move CLA yet so I think it should now be fine

**Comment by lgritz** [comment]
Yep, CLA looks good now, thanks.

But now you need the DCO!  The fix for that is just to `git commit --amend -s` which will add the "signed-off-by" line, and then `git push --force` your branch to update the PR.

There's a failed test for "Linux GPU", but that's unrelated to you, so don't worry about it. It looks like maybe something has changed in the nvidia headers that we download in order to do an OptiX build. I won't let that hold up your patch.

**Pull request merged**
