### PR TITLE
Change release notice icon to use the icon vs the normal logo so it shows up better

### PR DESCRIPTION
**Pull request by jmertic**
## Description

This fixed the icon used by the release notice to make it show up better.

## Tests

N/A

## Checklist:

- [ ] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [ ] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).
- [ ] My code follows the prevailing code style of this project. If I haven't
  already run clang-format v17 before submitting, I definitely will look at
  the CI test that runs clang-format and fix anything that it highlights as
  being nonconforming.

### CODE REVIEW

**Review by lgritz — APPROVED** [review]

**Comment by jmertic** [comment]
I know - working on it...

**Comment by lgritz** [comment]
@jmertic Reminder, this has been sitting for over a month

**Comment by lgritz** [comment]
@jmertic poke

**Comment by lgritz** [comment]
@jmertic

**Comment by jmertic** [comment]
@lgritz Finally!

**Pull request merged**
