### PR TITLE
Updated vector2.h with a mod function: mod(vector2,vector2);

### PR DESCRIPTION
**Pull request by gkmotu**
This is useful when working with vec2 concepts through out shaders like UV data for example.

I can provide a working example if needed.

## Checklist:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] I have previously submitted a [Contributor License Agreement](http://opensource.imageworks.com/cla/).
- [ ] I have updated the documentation, if applicable.
- [x] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project.

### CODE REVIEW

**Review by lgritz — COMMENTED** [review]
LGTM. Do you think that for symmetry, you should add the same functionality to vector4, color2, color4?

**Comment by gkmotu** [comment]
Makes perfect sense to add the 3 others.
I also have a distance function distance(vector4,vector4); used in production and implemented ( verified working locally ) I can submit.

**Comment by lgritz** [comment]
Sure, please do submit that one, too.

Mads, I'm going to need a CLA from you before I'm able to merge this PR.

**Comment by gkmotu** [comment]
OK,
I'll look at it today.

**Pull request merged**
