### PR TITLE
Add Visual Studio Code folder to gitignore

### PR DESCRIPTION
**Pull request by fpsunflower**
Just testing out commit workflow from windows 😄

### CODE REVIEW

**Review by lgritz — APPROVED** [review]

**Comment by lgritz** [comment]
Now all we need is Windows in our CI!

**Comment by fpsunflower** [comment]
I'll certainly try to think about this. The big one as you said is figuring out an easy way to pull the LLVM dependency.

It looks like I don't have write access to the repo to merge the PR ?

**Comment by lgritz** [comment]
Oops, I'm not sure how that happened. Maybe when you were removed from the imageworks org, we neglected to explicitly add you also as a committer to osl? Huge oversight. Invite sent; let me know if you're able to accept it and merge.

**Comment by fpsunflower** [comment]
All good! That's why I tested the waters with a trivial change :)

**Pull request merged**
