### PR TITLE
PR/FixBatchedPointCloud

### LINKED ISSUE #1750: Batched shading crashes in `pointcloud_search()`
### Problem

**Expected behavior:** `pointcloud_search()` returns the same result in batched shading mode as in regular mode.

**Actual behavior:** `pointcloud_search()` crashes in batched shading mode with the following stack trace :

```
#0  0x00007fff312a32de in OSL_v1_12::b16_AVX512_noFMA_pvt::(anonymous namespace)::default_pointcloud_search(OSL_v1_12::BatchedShaderGlobals<16>*, OpenImageIO_v2_4::ustring, void const*, OSL_v1_12::Wide<float const, 16>, int, bool, OSL_v1_12::BatchedRendererServices<16>::PointCloudSearchResults&)::{lambda(OSL_v1_12::ActiveLane)#1}::operator()(OSL_v1_12::ActiveLane) const () from /home/john/dev/build/gaffer-1.3/lib/lib_b16_AVX512_noFMA_oslexec.so
#1  0x00007fff312a947f in osl_b16_AVX512_noFMA_pointcloud_search_masked () from /home/john/dev/build/gaffer-1.3/lib/lib_b16_AVX512_noFMA_oslexec.so
#2  0x00007fffd58002ad in ?? ()
#3  0x0000000000000001 in ?? ()
#4  0x0000000000000000 in ?? ()
```

### Steps to Reproduce

1. Build OSL with the default Partio-based pointcloud services (I used Partio 1.14.6).
2. Write a shader that uses `pointcloud_search()` and run it in batched mode.

(These repro steps are a bit lame - I can probably come up with something more specific if the bug doesn't immediately jump out at you).

### Versions

* OSL branch/version:  1.12.9
* OS: CentOS 7
* C++ compiler:  GCC 9.3.1
* LLVM version: 11.1.0
* OIIO version: 2.4.11.0

### PR DESCRIPTION
**Pull request by AlexMWells**
Fixes #1750

## Description

Fix issue #1750: Batched shading crashes in point_cloud search if "index" is not passed as an attribute.

Fixed by allocating space for indices on stack before calling into underlying search algorithm which requires them (thus crashed if not provided).

## Tests

Added 2 new tests to exercise it with no indices provided and with indices array provided but not long enough.
   testsuite/pointcloud/rdcloud_varying_mismatch.osl
   testsuite/pointcloud/rdcloud_varying_no_index.osl

## Checklist:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] I have updated the documentation, if applicable.
- [x] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project. If I haven't
  already run clang-format before submitting, I definitely will look at the CI
  test that runs clang-format and fix anything that it highlights as being
  nonconforming.

### CODE REVIEW

**Comment by johnhaddon** [comment]
Thanks for jumping on this so quickly @AlexMWells!

**Comment by AlexMWells** [comment]
@lgritz this is ready for review/merge.  It also fixes up the failing CI for icx.

**Comment by lgritz** [comment]
BTW, don't mind the failure of the "bleeding edge" test -- this is due to something that broke in OpenColorIO's main branch. They have a fix under review currently, so I expect that to go back to passing in the coming days.

**Review by lgritz — APPROVED** [review]
LGTM, and thanks for the extra tests.

**Comment by lgritz** [comment]
Fixes #1750

**Pull request merged**
